[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
db_host = db
db_user = odoo
db_password = my_strong_odoo_password_123
admin_passwd = $pbkdf2-sha512$600000$xpgTwvgfY.wdg3Auxdj7Hw$JRPIDrtv/3CloBKkTMBeOUi5f4dGZpR/g5JqgT8QgvKkHTf0h4GmvPSixfRSeed8DakPzFwGi8GI3b9CCneTDw

