[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
db_host = db
db_user = odoo
admin_passwd = $pbkdf2-sha512$600000$be39H0MoxTjnXMv5H6MU4g$1/NcbxBY29AiViPnsLfchrUOUuAK82XA07LLdlyhF1zsA1E8H.glik63X2clY/gnjDHRGnPfwUu7lpJYKo0mMg

